# Generated by Django 2.2.4 on 2020-08-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=120, null=True)),
                ('batch', models.CharField(blank=True, max_length=120, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=120, null=True)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('picture', models.ImageField(upload_to='pictures')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
