# Generated by Django 2.2.4 on 2020-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userregis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
