# Generated by Django 2.2.4 on 2020-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200825_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegis',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
