# Generated by Django 2.2.4 on 2020-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
