# Generated by Django 2.2.4 on 2020-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.CharField(choices=[('Sedentary', 'GREEN'), ('lightly active', 'BLUE'), ('moderately active', 'RED'), ('very active', 'ORANGE'), ('extra active', 'BLACK')], default='Sedentary', max_length=120),
        ),
    ]
