# Generated by Django 2.2.4 on 2020-10-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active'), ('Extra Active', 'Extra Active')], default='Sedentary', max_length=120),
        ),
    ]
