# Generated by Django 2.2.4 on 2020-10-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alert_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie_intake',
            old_name='momday',
            new_name='monday',
        ),
        migrations.RemoveField(
            model_name='calorie_disturb',
            name='momday',
        ),
        migrations.AddField(
            model_name='calorie_disturb',
            name='monday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='alert_button',
            name='alert_button',
            field=models.CharField(blank=True, default='on', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='friday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='saturday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='sunday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='thursday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='tuesday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='wednesday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
    ]
