# Generated by Django 2.2.4 on 2020-10-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201021_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_disturb',
            name='friday',
            field=models.CharField(blank=True, default='No', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='monday',
            field=models.CharField(blank=True, default='No', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='saturday',
            field=models.CharField(blank=True, default='No', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='sunday',
            field=models.CharField(blank=True, default='No', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='thursday',
            field=models.CharField(blank=True, default='No', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='tuesday',
            field=models.CharField(blank=True, default='No', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='wednesday',
            field=models.CharField(blank=True, default='No', max_length=120, null=True),
        ),
    ]
