# Generated by Django 2.2.4 on 2020-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201022_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_disturb',
            name='friday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='monday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='saturday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='sunday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='thursday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='tuesday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_disturb',
            name='wednesday',
            field=models.CharField(blank=True, default='no', max_length=120, null=True),
        ),
    ]
