# Generated by Django 2.2.4 on 2020-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_calorie_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie_record',
            old_name='Daynumber',
            new_name='friday',
        ),
        migrations.AddField(
            model_name='calorie_record',
            name='momday',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='calorie_record',
            name='saturday',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='calorie_record',
            name='sunday',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='calorie_record',
            name='thursday',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='calorie_record',
            name='tuesday',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='calorie_record',
            name='wednesday',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
