# Generated by Django 2.2.4 on 2020-10-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201007_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_record',
            name='friday',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_record',
            name='momday',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_record',
            name='saturday',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_record',
            name='sunday',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_record',
            name='thursday',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_record',
            name='tuesday',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calorie_record',
            name='wednesday',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
    ]
