# Generated by Django 2.2.4 on 2020-10-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201007_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calorie_intake',
            name='user',
        ),
        migrations.DeleteModel(
            name='Calorie_Disturb',
        ),
        migrations.DeleteModel(
            name='Calorie_Intake',
        ),
    ]
