# Generated by Django 2.2.4 on 2020-10-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201007_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
