# Generated by Django 2.2.4 on 2020-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201115_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='Files')),
            ],
        ),
    ]
