# Generated by Django 2.2.4 on 2020-11-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_photostore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoStore',
        ),
    ]
